import {
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE
} from '@/constants/navigation.constant'
import { OWNER, MANAGER, ADMIN } from '@/constants/roles.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    // OWNER MENU
    {
        key: 'ownerDashboard',
        path: '/owner/dashboard',
        title: 'داشبورد',
        translateKey: 'nav.owner.dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [OWNER],
        subMenu: [],
    },
    {
        key: 'ownerOrganization',
        path: '',
        title: 'سازمان',
        translateKey: 'nav.owner.organization',
        icon: 'building',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [OWNER],
        subMenu: [
            {
                key: 'ownerCompany',
                path: '/owner/company',
                title: 'پروفایل سازمان',
                translateKey: 'nav.owner.company',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER],
                subMenu: [],
            },
            {
                key: 'ownerPayments',
                path: '/owner/payments',
                title: 'پرداخت‌ها',
                translateKey: 'nav.owner.payments',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER],
                subMenu: [],
            },
            {
                key: 'ownerPaymentsHistory',
                path: '/owner/payments/history',
                title: 'تاریخچه پرداخت',
                translateKey: 'nav.owner.payments.history',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER],
                subMenu: [],
            },
        ],
    },
    {
        key: 'ownerManagers',
        path: '',
        title: 'مدیران',
        translateKey: 'nav.owner.managers',
        icon: 'users',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [OWNER],
        subMenu: [
            {
                key: 'ownerManagersList',
                path: '/owner/managers',
                title: 'لیست مدیران',
                translateKey: 'nav.owner.managers.list',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER],
                subMenu: [],
            },
            {
                key: 'ownerManagersAdd',
                path: '/owner/managers/add',
                title: 'افزودن مدیر',
                translateKey: 'nav.owner.managers.add',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER],
                subMenu: [],
            },
        ],
    },
    {
        key: 'ownerAssessmentExams',
        path: '',
        title: 'نیازسنجی و آزمون',
        translateKey: 'nav.owner.assessment.exams',
        icon: 'clipboardList',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [OWNER],
        subMenu: [
            {
                key: 'ownerAssessment',
                path: '/owner/assessment',
                title: 'نیازسنجی',
                translateKey: 'nav.owner.assessment',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER],
                subMenu: [],
            },
            {
                key: 'ownerExams',
                path: '/owner/exams',
                title: 'آزمون‌ها',
                translateKey: 'nav.owner.exams',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER],
                subMenu: [],
            },
            {
                key: 'ownerExamsAssigned',
                path: '/owner/exams/assigned',
                title: 'اختصاص داده شده',
                translateKey: 'nav.owner.exams.assigned',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER],
                subMenu: [],
            },
            {
                key: 'ownerExamsResults',
                path: '/owner/exams/results',
                title: 'نتایج آزمون',
                translateKey: 'nav.owner.exams.results',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER],
                subMenu: [],
            },
        ],
    },
    {
        key: 'ownerResults',
        path: '/owner/results',
        title: 'نتایج',
        translateKey: 'nav.owner.results',
        icon: 'chartBar',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [OWNER],
        subMenu: [],
    },
    {
        key: 'ownerReports',
        path: '/owner/reports',
        title: 'گزارش‌ها',
        translateKey: 'nav.owner.reports',
        icon: 'documentReport',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [OWNER],
        subMenu: [],
    },
    {
        key: 'ownerAccount',
        path: '',
        title: 'حساب کاربری',
        translateKey: 'nav.owner.account',
        icon: 'user',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [OWNER],
        subMenu: [
            {
                key: 'ownerNotifications',
                path: '/owner/notifications',
                title: 'اعلان‌ها',
                translateKey: 'nav.owner.notifications',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER],
                subMenu: [],
            },
            {
                key: 'ownerProfile',
                path: '/owner/profile',
                title: 'پروفایل',
                translateKey: 'nav.owner.profile',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER],
                subMenu: [],
            },
            {
                key: 'ownerSupport',
                path: '/owner/support',
                title: 'پشتیبانی',
                translateKey: 'nav.owner.support',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER],
                subMenu: [],
            },
        ],
    },

    // MANAGER MENU
    {
        key: 'managerDashboard',
        path: '/manager/dashboard',
        title: 'داشبورد',
        translateKey: 'nav.manager.dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [MANAGER],
        subMenu: [],
    },
    {
        key: 'managerExams',
        path: '',
        title: 'آزمون‌ها',
        translateKey: 'nav.manager.exams',
        icon: 'clipboardList',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [MANAGER],
        subMenu: [
            {
                key: 'managerExamsList',
                path: '/manager/exams',
                title: 'لیست آزمون‌ها',
                translateKey: 'nav.manager.exams.list',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [MANAGER],
                subMenu: [],
            },
            {
                key: 'managerExamsActive',
                path: '/manager/exams/active',
                title: 'آزمون‌های فعال',
                translateKey: 'nav.manager.exams.active',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [MANAGER],
                subMenu: [],
            },
        ],
    },
    {
        key: 'managerResults',
        path: '/manager/results',
        title: 'نتایج من',
        translateKey: 'nav.manager.results',
        icon: 'chartBar',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [MANAGER],
        subMenu: [],
    },
    {
        key: 'managerAccount',
        path: '',
        title: 'حساب کاربری',
        translateKey: 'nav.manager.account',
        icon: 'user',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [MANAGER],
        subMenu: [
            {
                key: 'managerNotifications',
                path: '/manager/notifications',
                title: 'اعلان‌ها',
                translateKey: 'nav.manager.notifications',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [MANAGER],
                subMenu: [],
            },
            {
                key: 'managerProfile',
                path: '/manager/profile',
                title: 'پروفایل',
                translateKey: 'nav.manager.profile',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [MANAGER],
                subMenu: [],
            },
            {
                key: 'managerSupport',
                path: '/manager/support',
                title: 'پشتیبانی',
                translateKey: 'nav.manager.support',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [MANAGER],
                subMenu: [],
            },
        ],
    },

    // ADMIN MENU
    {
        key: 'adminDashboard',
        path: '/admin/dashboard',
        title: 'داشبورد',
        translateKey: 'nav.admin.dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [],
    },
    {
        key: 'adminOrganizations',
        path: '',
        title: 'سازمان‌ها',
        translateKey: 'nav.admin.organizations',
        icon: 'building',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN],
        subMenu: [
            {
                key: 'adminCompanies',
                path: '/admin/companies',
                title: 'لیست سازمان‌ها',
                translateKey: 'nav.admin.companies',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'adminOwners',
                path: '/admin/owners',
                title: 'مدیرعامل‌ها',
                translateKey: 'nav.admin.owners',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'adminManagers',
                path: '/admin/managers',
                title: 'مدیران',
                translateKey: 'nav.admin.managers',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
        ],
    },
    {
        key: 'adminAssessment',
        path: '',
        title: 'نیازسنجی',
        translateKey: 'nav.admin.assessment',
        icon: 'clipboardCheck',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN],
        subMenu: [
            {
                key: 'adminAssessmentForms',
                path: '/admin/assessment/forms',
                title: 'فرم‌های نیازسنجی',
                translateKey: 'nav.admin.assessment.forms',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
        ],
    },
    {
        key: 'adminExams',
        path: '',
        title: 'آزمون‌ها',
        translateKey: 'nav.admin.exams',
        icon: 'clipboardList',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN],
        subMenu: [
            {
                key: 'adminExamsList',
                path: '/admin/exams',
                title: 'لیست آزمون‌ها',
                translateKey: 'nav.admin.exams.list',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'adminExamsAdd',
                path: '/admin/exams/add',
                title: 'افزودن آزمون',
                translateKey: 'nav.admin.exams.add',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'adminQuestions',
                path: '/admin/questions',
                title: 'بانک سوال',
                translateKey: 'nav.admin.questions',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'adminQuestionsAdd',
                path: '/admin/questions/add',
                title: 'افزودن سوال',
                translateKey: 'nav.admin.questions.add',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'adminAnswers',
                path: '/admin/answers',
                title: 'پاسخ‌ها',
                translateKey: 'nav.admin.answers',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
        ],
    },
    {
        key: 'adminReportsPayments',
        path: '',
        title: 'گزارش و پرداخت',
        translateKey: 'nav.admin.reports.payments',
        icon: 'documentReport',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN],
        subMenu: [
            {
                key: 'adminReports',
                path: '/admin/reports',
                title: 'گزارش‌ها',
                translateKey: 'nav.admin.reports',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'adminPayments',
                path: '/admin/payments',
                title: 'پرداخت‌ها',
                translateKey: 'nav.admin.payments',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
        ],
    },
    {
        key: 'adminCommunications',
        path: '',
        title: 'ارتباطات',
        translateKey: 'nav.admin.communications',
        icon: 'chatBubbleLeftRight',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN],
        subMenu: [
            {
                key: 'adminNotifications',
                path: '/admin/notifications',
                title: 'اعلان‌ها',
                translateKey: 'nav.admin.notifications',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'adminSms',
                path: '/admin/sms',
                title: 'پیامک‌ها',
                translateKey: 'nav.admin.sms',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'adminTemplates',
                path: '/admin/templates',
                title: 'قالب پیام',
                translateKey: 'nav.admin.templates',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
        ],
    },
    {
        key: 'adminSystemSettings',
        path: '',
        title: 'تنظیمات سیستم',
        translateKey: 'nav.admin.system.settings',
        icon: 'cog',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN],
        subMenu: [
            {
                key: 'adminSettings',
                path: '/admin/settings',
                title: 'تنظیمات',
                translateKey: 'nav.admin.settings',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'adminRoles',
                path: '/admin/roles',
                title: 'نقش‌ها و دسترسی',
                translateKey: 'nav.admin.roles',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
