import {
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE
} from '@/constants/navigation.constant'
import { OWNER, MANAGER, ADMIN } from '@/constants/roles.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    // OWNER MENU
    {
        key: 'ownerDashboard',
        path: '/owner/dashboard',
        title: 'داشبورد',
        translateKey: 'nav.owner.dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [OWNER],
        subMenu: [],
    },
    {
        key: 'ownerCompanies',
        path: '/owner/companies',
        title: 'سازمان های من',
        translateKey: 'nav.owner.companies',
        icon: 'building',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [OWNER],
        subMenu: [],
    },
    {
        key: 'ownerManagers',
        path: '/owner/managers',
        title: 'متقاضیان',
        translateKey: 'nav.owner.managers',
        icon: 'users',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [OWNER],
        subMenu: [],
    },
    {
        key: 'ownerExamsAndResults',
        path: '/owner/exams-results',
        title: 'آزمون‌ها و نتایج',
        translateKey: 'nav.owner.examsResults',
        icon: 'checkCircle',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [OWNER],
        subMenu: [],
    },
    {
        key: 'ownerAccounting',
        path: '',
        title: 'امور مالی',
        translateKey: 'nav.owner.accounting',
        icon: 'cash',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [OWNER],
        subMenu: [
            {
                key: 'ownerFinancialDocuments',
                path: '/owner/accounting/documents',
                title: 'اسناد مالی',
                translateKey: 'nav.owner.accounting.documents',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER],
                subMenu: [],
            },
            {
                key: 'ownerBills',
                path: '/owner/accounting/bills',
                title: 'صورتحساب‌ها',
                translateKey: 'nav.owner.accounting.bills',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER],
                subMenu: [],
            },
        ],
    },
    {
        key: 'ownerAccount',
        path: '',
        title: 'حساب کاربری',
        translateKey: 'nav.owner.account',
        icon: 'user',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [OWNER],
        subMenu: [

            {
                key: 'ownerUserProfile',
                path: '/owner/user-profile',
                title: 'تنظیمات کاربری',
                translateKey: 'nav.owner.userProfile',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER],
                subMenu: [],
            },
        ],
    },
    {
        key: 'ownerSupport',
        path: '',
        title: 'پشتیبانی',
        translateKey: 'nav.owner.support',
        icon: 'support',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [OWNER],
        subMenu: [
            {
                key: 'ownerSupportTickets',
                path: '/owner/support/tickets',
                title: 'تیکت‌ها',
                translateKey: 'nav.owner.support.tickets',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER],
                subMenu: [],
            },
            {
                key: 'ownerSupportCreate',
                path: '/owner/support/create',
                title: 'ایجاد تیکت',
                translateKey: 'nav.owner.support.create',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER],
                subMenu: [],
            },
            {
                key: 'ownerSupportContact',
                path: '/owner/support/contact',
                title: 'تماس مستقیم',
                translateKey: 'nav.owner.support.contact',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER],
                subMenu: [],
            },
        ],
    },
    {
        key: 'ownerNotifications',
        path: '/owner/notifications',
        title: 'اعلان‌ها',
        translateKey: 'nav.owner.notifications',
        icon: 'bell',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [OWNER],
        subMenu: [],
    },

    // MANAGER MENU
    {
        key: 'managerDashboard',
        path: '/manager/dashboard',
        title: 'داشبورد',
        translateKey: 'nav.manager.dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [MANAGER],
        subMenu: [],
    },
    {
        key: 'managerExams',
        path: '',
        title: 'آزمون‌ها',
        translateKey: 'nav.manager.exams',
        icon: 'clipboardList',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [MANAGER],
        subMenu: [
            {
                key: 'managerExamsList',
                path: '/manager/exams',
                title: 'لیست آزمون‌ها',
                translateKey: 'nav.manager.exams.list',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [MANAGER],
                subMenu: [],
            },
            {
                key: 'managerExamsActive',
                path: '/manager/exams/active',
                title: 'آزمون‌های فعال',
                translateKey: 'nav.manager.exams.active',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [MANAGER],
                subMenu: [],
            },
        ],
    },
    {
        key: 'managerResults',
        path: '/manager/results',
        title: 'نتایج من',
        translateKey: 'nav.manager.results',
        icon: 'chartBar',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [MANAGER],
        subMenu: [],
    },
    {
        key: 'managerAccount',
        path: '',
        title: 'حساب کاربری',
        translateKey: 'nav.manager.account',
        icon: 'user',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [MANAGER],
        subMenu: [
            {
                key: 'managerNotifications',
                path: '/manager/notifications',
                title: 'اعلان‌ها',
                translateKey: 'nav.manager.notifications',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [MANAGER],
                subMenu: [],
            },
            {
                key: 'managerProfile',
                path: '/manager/profile',
                title: 'پروفایل',
                translateKey: 'nav.manager.profile',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [MANAGER],
                subMenu: [],
            },
            {
                key: 'managerSupport',
                path: '/manager/support',
                title: 'پشتیبانی',
                translateKey: 'nav.manager.support',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [MANAGER],
                subMenu: [],
            },
        ],
    },

    // ADMIN MENU
    {
        key: 'adminDashboard',
        path: '/admin/dashboard',
        title: 'داشبورد',
        translateKey: 'nav.admin.dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [],
    },
    {
        key: 'adminOrganizations',
        path: '/admin/companies',
        title: 'سازمان‌ها',
        translateKey: 'nav.admin.organizations',
        icon: 'building',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [],
    },
    {
        key: 'adminCompletedAssessments',
        path: '/admin/assessments/completed',
        title: 'نیازسنجی‌های تکمیل شده',
        translateKey: 'nav.admin.assessments.completed',
        icon: 'clipboardCheck',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [],
    },
    {
        key: 'adminApplicantExams',
        path: '/admin/applicant-exams',
        title: 'آزمون‌های متقاضیان',
        translateKey: 'nav.admin.applicant.exams',
        icon: 'academicCap',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [],
    },
    {
        key: 'adminConfiguration',
        path: '',
        title: 'پیکربندی',
        translateKey: 'nav.admin.configuration',
        icon: 'cog',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN],
        subMenu: [
            {
                key: 'adminAssessmentForms',
                path: '/admin/assessment/forms',
                title: 'فرم نیازسنجی',
                translateKey: 'nav.admin.assessment.forms',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'adminExams',
                path: '/admin/exams',
                title: 'آزمون‌ها',
                translateKey: 'nav.admin.exams',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
        ],
    },

    {
        key: 'adminReportsPayments',
        path: '',
        title: 'گزارش و پرداخت',
        translateKey: 'nav.admin.reports.payments',
        icon: 'documentReport',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN],
        subMenu: [
            {
                key: 'adminReports',
                path: '/admin/reports',
                title: 'گزارش‌ها',
                translateKey: 'nav.admin.reports',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'adminPayments',
                path: '/admin/payments',
                title: 'پرداخت‌ها',
                translateKey: 'nav.admin.payments',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
        ],
    },
    {
        key: 'adminCommunications',
        path: '',
        title: 'ارتباطات',
        translateKey: 'nav.admin.communications',
        icon: 'chatBubbleLeftRight',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN],
        subMenu: [
            {
                key: 'adminSupportTickets',
                path: '/admin/support/tickets',
                title: 'تیکت‌های پشتیبانی',
                translateKey: 'nav.admin.support.tickets',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'adminNotifications',
                path: '/admin/notifications',
                title: 'اعلان‌ها',
                translateKey: 'nav.admin.notifications',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'adminSms',
                path: '/admin/sms',
                title: 'پیامک‌ها',
                translateKey: 'nav.admin.sms',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'adminTemplates',
                path: '/admin/templates',
                title: 'قالب پیام',
                translateKey: 'nav.admin.templates',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
        ],
    },
    {
        key: 'adminSystemSettings',
        path: '/admin/settings',
        title: 'تنظیمات کاربری',
        translateKey: 'nav.admin.system.settings',
        icon: 'user',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [],
    },
]

export default navigationConfig
