import {
    PiHouseLineDuotone,
    PiArrowsInDuotone,
    PiBookOpenUserDuotone,
    PiBookBookmarkDuotone,
    PiAcornDuotone,
    PiBagSimpleDuotone,
    PiSquaresFourDuotone,
    PiBuildingDuotone,
    PiUsersDuotone,
    PiClipboardTextDuotone,
    PiChartBarDuotone,
    PiFileTextDuotone,
    PiCreditCardDuotone,
    PiBellDuotone,
    PiUserDuotone,
    PiHeadphonesDuotone,
    PiUserCircleDuotone,
    PiClipboardDuotone,
    PiQuestionDuotone,
    PiCheckCircleDuotone,
    PiChatCircleTextDuotone,
    PiFileDuotone,
    PiGearDuotone,
    PiShieldCheckDuotone,
    PiCurrencyDollarSimpleDuotone,
    PiGraduationCapDuotone
} from 'react-icons/pi'

export type NavigationIcons = Record<string, JSX.Element>

const navigationIcon: NavigationIcons = {
    home: <PiHouseLineDuotone />,
    singleMenu: <PiAcornDuotone />,
    collapseMenu: <PiArrowsInDuotone />,
    groupSingleMenu: <PiBookOpenUserDuotone />,
    groupCollapseMenu: <PiBookBookmarkDuotone />,
    groupMenu: <PiBagSimpleDuotone />,
    dashboard: <PiSquaresFourDuotone />,
    building: <PiBuildingDuotone />,
    users: <PiUsersDuotone />,
    clipboardList: <PiClipboardTextDuotone />,
    chartBar: <PiChartBarDuotone />,
    documentReport: <PiFileTextDuotone />,
    creditCard: <PiCreditCardDuotone />,
    bell: <PiBellDuotone />,
    user: <PiUserDuotone />,
    support: <PiHeadphonesDuotone />,
    userGroup: <PiUserCircleDuotone />,
    clipboardCheck: <PiClipboardDuotone />,
    questionMarkCircle: <PiQuestionDuotone />,
    checkCircle: <PiCheckCircleDuotone />,
    chatBubbleLeftRight: <PiChatCircleTextDuotone />,
    documentText: <PiFileDuotone />,
    cog: <PiGearDuotone />,
    shieldCheck: <PiShieldCheckDuotone />,
    cash: <PiCurrencyDollarSimpleDuotone />,
    academicCap: <PiGraduationCapDuotone />
}

export default navigationIcon
