import { lazy } from 'react'
import { ADMIN } from '@/constants/roles.constant'
import type { Routes } from '@/@types/routes'

const adminRoutes: Routes = [
    {
        key: 'adminDashboard',
        path: '/admin/dashboard',
        component: lazy(() => import('@/views/admin/Dashboard')),
        authority: [ADMIN],
    },
    {
        key: 'adminCompanies',
        path: '/admin/companies',
        component: lazy(() => import('@/views/admin/Companies')),
        authority: [ADMIN],
    },
    {
        key: 'adminCompanyDetails',
        path: '/admin/companies/:id',
        component: lazy(() => import('@/views/admin/CompanyDetails')),
        authority: [ADMIN],
    },
    {
        key: 'adminCompanyEdit',
        path: '/admin/companies/:id/edit',
        component: lazy(() => import('@/views/admin/CompanyEdit')),
        authority: [ADMIN],
    },
    {
        key: 'adminCompanyManagers',
        path: '/admin/companies/:companyId/managers',
        component: lazy(() => import('@/views/admin/CompanyManagers')),
        authority: [ADMIN],
    },
    {
        key: 'adminCompanyManagerAdd',
        path: '/admin/companies/:companyId/managers/add',
        component: lazy(() => import('@/views/admin/CompanyManagerAdd')),
        authority: [ADMIN],
    },
    {
        key: 'adminCompanyManagerEdit',
        path: '/admin/companies/:companyId/managers/:managerId/edit',
        component: lazy(() => import('@/views/admin/CompanyManagerAdd')),
        authority: [ADMIN],
    },
    {
        key: 'adminCompanyManagerDetails',
        path: '/admin/companies/:companyId/managers/:managerId',
        component: lazy(() => import('@/views/admin/CompanyManagerDetails')),
        authority: [ADMIN],
    },
    {
        key: 'adminOwners',
        path: '/admin/owners',
        component: lazy(() => import('@/views/admin/Owners')),
        authority: [ADMIN],
    },
    {
        key: 'adminOwnerDetails',
        path: '/admin/owners/:ownerId',
        component: lazy(() => import('@/views/admin/OwnerDetails')),
        authority: [ADMIN],
    },
    {
        key: 'adminManagers',
        path: '/admin/managers',
        component: lazy(() => import('@/views/admin/Managers')),
        authority: [ADMIN],
    },
    {
        key: 'adminManagerDetails',
        path: '/admin/managers/:managerId',
        component: lazy(() => import('@/views/admin/ManagerDetails')),
        authority: [ADMIN],
    },
    {
        key: 'adminCompletedAssessments',
        path: '/admin/assessments/completed',
        component: lazy(() => import('@/views/admin/CompletedAssessments')),
        authority: [ADMIN],
    },
    {
        key: 'adminCompletedAssessmentView',
        path: '/admin/assessments/:id',
        component: lazy(() => import('@/views/admin/CompletedAssessmentView')),
        authority: [ADMIN],
    },
    {
        key: 'adminApplicantExams',
        path: '/admin/applicant-exams',
        component: lazy(() => import('@/views/admin/ApplicantExamSets')),
        authority: [ADMIN],
    },
    {
        key: 'adminApplicantExamResults',
        path: '/admin/applicant-exams/:examSetId/results',
        component: lazy(() => import('@/views/admin/ApplicantExamResults')),
        authority: [ADMIN],
    },
    {
        key: 'adminAssessmentForms',
        path: '/admin/assessment/forms',
        component: lazy(() => import('@/views/admin/AssessmentForms')),
        authority: [ADMIN],
    },
    {
        key: 'adminExams',
        path: '/admin/exams',
        component: lazy(() => import('@/views/admin/Exams')),
        authority: [ADMIN],
    },
    {
        key: 'adminCreateExam',
        path: '/admin/exams/create',
        component: lazy(() => import('@/views/admin/CreateExam')),
        authority: [ADMIN],
    },
    {
        key: 'adminAssessmentForm',
        path: '/admin/assessment/:assessmentId',
        component: lazy(() => import('@/views/admin/AssessmentForm')),
        authority: [ADMIN],
    },
    {
        key: 'adminExams',
        path: '/admin/exams',
        component: lazy(() => import('@/views/admin/Exams')),
        authority: [ADMIN],
    },
    {
        key: 'adminExamsAdd',
        path: '/admin/exams/add',
        component: lazy(() => import('@/views/admin/ExamsAdd')),
        authority: [ADMIN],
    },
    {
        key: 'adminExamDetails',
        path: '/admin/exams/:examId',
        component: lazy(() => import('@/views/admin/ExamDetails')),
        authority: [ADMIN],
    },
    {
        key: 'adminExamsAssign',
        path: '/admin/exams/assign/:managerId',
        component: lazy(() => import('@/views/admin/ExamsAssign')),
        authority: [ADMIN],
    },
    {
        key: 'adminQuestions',
        path: '/admin/questions',
        component: lazy(() => import('@/views/admin/Questions')),
        authority: [ADMIN],
    },
    {
        key: 'adminQuestionsAdd',
        path: '/admin/questions/add',
        component: lazy(() => import('@/views/admin/QuestionsAdd')),
        authority: [ADMIN],
    },
    {
        key: 'adminQuestionDetails',
        path: '/admin/questions/:questionId',
        component: lazy(() => import('@/views/admin/QuestionDetails')),
        authority: [ADMIN],
    },
    {
        key: 'adminAnswers',
        path: '/admin/answers',
        component: lazy(() => import('@/views/admin/Answers')),
        authority: [ADMIN],
    },
    {
        key: 'adminAnswersManager',
        path: '/admin/answers/:managerId',
        component: lazy(() => import('@/views/admin/AnswersManager')),
        authority: [ADMIN],
    },
    {
        key: 'adminAccounting',
        path: '/admin/accounting',
        component: lazy(() => import('@/views/admin/Accounting')),
        authority: [ADMIN],
    },
    {
        key: 'adminFinancialDocuments',
        path: '/admin/accounting/documents',
        component: lazy(() => import('@/views/admin/FinancialDocuments')),
        authority: [ADMIN],
    },
    {
        key: 'adminFinancialDocumentView',
        path: '/admin/accounting/documents/:id',
        component: lazy(() => import('@/views/admin/FinancialDocumentView')),
        authority: [ADMIN],
    },
    {
        key: 'adminBills',
        path: '/admin/accounting/bills',
        component: lazy(() => import('@/views/admin/Bills')),
        authority: [ADMIN],
    },
    {
        key: 'adminBillView',
        path: '/admin/accounting/bills/:id',
        component: lazy(() => import('@/views/admin/BillView')),
        authority: [ADMIN],
    },
    {
        key: 'adminNotifications',
        path: '/admin/notifications',
        component: lazy(() => import('@/views/admin/Notifications')),
        authority: [ADMIN],
    },
    {
        key: 'adminSms',
        path: '/admin/sms',
        component: lazy(() => import('@/views/admin/Sms')),
        authority: [ADMIN],
    },
    {
        key: 'adminTemplates',
        path: '/admin/templates',
        component: lazy(() => import('@/views/admin/Templates')),
        authority: [ADMIN],
    },
    {
        key: 'adminSystemSettings',
        path: '/admin/settings',
        component: lazy(() => import('@/views/admin/Settings')),
        authority: [ADMIN],
    },
    {
        key: 'adminRoles',
        path: '/admin/roles',
        component: lazy(() => import('@/views/admin/Roles')),
        authority: [ADMIN],
    },
    {
        key: 'adminSupportTickets',
        path: '/admin/support/tickets',
        component: lazy(() => import('@/views/admin/Support')),
        authority: [ADMIN],
    },
    {
        key: 'adminSupportCreate',
        path: '/admin/support/create',
        component: lazy(() => import('@/views/admin/CreateTicket')),
        authority: [ADMIN],
    },
    {
        key: 'adminSupportTicketView',
        path: '/admin/support/ticket/:ticketId',
        component: lazy(() => import('@/views/admin/SupportTicketView')),
        authority: [ADMIN],
    },
]

export default adminRoutes